// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package feed

import (
	"github.com/koykov/demo/wirex/internal/http/request"
)

// Injectors from wire.go:

func Wire(dlv request.Deliveler, mc *request.ModelContainer) *Handler {
	repository := ProvideRepository(dlv, mc)
	service := ProvideService(repository)
	handler := ProvideHandler(service)
	return handler
}
