{
 "title": "Default",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "queue", "query": { "query": "label_values(queue)" } }
  ]
 },
 "panels": [
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(queue_size{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} size"
    }
   ]
  },
  {
   "title": "Queue bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(queue_in{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} in"
    },
    {
     "expr": "sum(irate(queue_out{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} out"
    },
    {
     "expr": "sum(irate(queue_leak{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} leak"
    },
    {
     "expr": "sum(irate(queue_lost{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} lost"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(queue_workers_active{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} active"
    },
    {
     "expr": "sum(queue_workers_sleep{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} sleep"
    },
    {
     "expr": "sum(queue_workers_idle{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} idle"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(queue_producers_active{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} active"
    },
    {
     "expr": "sum(queue_producers_idle{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} idle"
    }
   ]
  },
  {
   "title": "DLQ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(dlqdump_size_in{queue=\"$queue\"}[1m])",
     "legendFormat": "leak items"
    },
    {
     "expr": "rate(dlqdump_bytes_in{queue=\"$queue\"}[1m])",
     "legendFormat": "leak bytes"
    },
    {
     "expr": "rate(dlqdump_bytes_flush{queue=\"$queue\"}[1m])",
     "legendFormat": "flush bytes by {{reason}}"
    }
   ]
  },
  {
   "title": "Restorer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(dlqdump_size_out{queue=\"$queue\"}[1m])",
     "legendFormat": "restore items"
    },
    {
     "expr": "rate(dlqdump_bytes_out{queue=\"$queue\"}[1m])",
     "legendFormat": "restore bytes"
    }
   ]
  },
  {
   "title": "Delayed execution wait (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, queue) (rate(queue_wait_bucket{queue=\"$queue\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}