{
 "title": "Balanced leaky queue",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "queue", "query": { "query": "label_values(queue)" } }
  ]
 },
 "panels": [
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(blqueue_size{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} size"
    }
   ]
  },
  {
   "title": "Queue bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(blqueue_in{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} in"
    },
    {
     "expr": "sum(irate(blqueue_out{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} out"
    },
    {
     "expr": "sum(irate(blqueue_leak{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} leak"
    },
    {
     "expr": "sum(irate(blqueue_lost{queue=\"$queue\"}[30s])) by (queue)",
     "legendFormat": "{{queue}} lost"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(blqueue_workers_active{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} active"
    },
    {
     "expr": "sum(blqueue_workers_sleep{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} sleep"
    },
    {
     "expr": "sum(blqueue_workers_idle{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} idle"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(blqueue_producers_active{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} active"
    },
    {
     "expr": "sum(blqueue_producers_idle{queue=\"$queue\"}) by (queue)",
     "legendFormat": "{{queue}} idle"
    }
   ]
  },
  {
   "title": "Delayed execution wait (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, queue) (rate(blqueue_wait_bucket{queue=\"$queue\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}