### init
POST http://localhost:8080/api/v1/init?key=cache1G
Content-Type: application/json

{
  "buckets": 1,
  "expire_interval_ns": 30000000000,
  "capacity": 1073741824,
  "collision_check": true,
  "vacuum_interval_ns": 60000000000,
  "metrics_key": "demo1G",
  "force_set": true,
  "writers": 8,
  "writer_krp": 10,
  "writer_delay": 1000000,
  "readers": 8,
  "reader_delay": 1000000
}
